name = "edge-signal"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "Room" },
  { name = "REGISTRY", class_name = "Registry" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room", "Registry"]

[assets]
directory = "public"
binding = "ASSETS"

[vars]
NAT_PUNCH_STAGGER_MS = "1000"
NAT_SENDER_DISPATCH_DELAY_MS = "1000"
UUID = "2523c510-9ff0-415b-9582-93949bfae7e3"
